---

charts:
  - name: qubership-zookeeper
    chart_file: charts/helm/zookeeper-service/Chart.yaml
    values_file: charts/helm/zookeeper-service/values.yaml
    image:
      - ghcr.io/netcracker/qubership-zookeeper-operator:#0.*.4
      - ghcr.io/netcracker/qubership-docker-zookeeper:${release}
      - ghcr.io/netcracker/qubership-zookeeper-backup-daemon:#latest
      - ghcr.io/netcracker/qubership-zookeeper-integration-tests:${release}-${ZOO_VERSION}
      - ghcr.io/netcracker/qubership-disaster-recovery-daemon:#v0.4.*
