name: "Go: CI Build and Test"
run-name: "Ref: ${{ github.ref_name }}. On ${{ github.event_name }}"

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "*.md"
      - "LICENSE"

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: borislavr/qubership-zookeeper/.github/workflows/re-go-ci.yml@main
    with:
      working-directory: "."
      go-version: "1.23"
      run-sonar: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
